# Basket option implementation based on normal model

In [70]:
import numpy as np
from option_models import basket
from option_models import bsm
from option_models import normal

In [71]:
### only run this when you changed the class definition
import imp
imp.reload(basket)

<module 'option_models.basket' from 'D:\\Mega\\PHBS\\@ASP\\2018.M1.ASP\\py\\option_models\\basket.py'>

In [72]:
# A trivial test case 1: 
# one asset have 100% weight (the others zero)
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.array([1, 0, 0, 0])
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 120

print(weights)

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)

[1 0 0 0]


In [73]:
# Compare the price to normal model formula

norm1 = normal.NormalModel(40)
price_norm = norm1.price(strike=120, spot=100, texp=texp, cp_sign=1)
print(price_basket, price_norm)

26.763909734339606 26.570845957870503


In [74]:
# A trivial test case 2

# all assets almost perfectly correlated:
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.0001*np.identity(4) + 0.9999*np.ones((4,4))
texp = 5
strike = 120

print( cor_m )

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)
print(price_basket, price_norm)

[[1.     0.9999 0.9999 0.9999]
 [0.9999 1.     0.9999 0.9999]
 [0.9999 0.9999 1.     0.9999]
 [0.9999 0.9999 0.9999 1.    ]]
26.761395615904505 26.570845957870503


In [75]:
# A test set for basket option with exact price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 100

price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)
price_exact = 28.0073695

print(price_basket, price_exact)

28.168716545630815 28.0073695


# [To Do] Basket option implementation based on BSM model
## Write the similar test

In [76]:
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)

# Spread option implementation based on normal model

In [77]:
# A test set for spread option

spot = np.array([100, 96])
vol = np.array([0.2, 0.1])
weights = np.array([1, -1])
divr = np.array([1, 1])*0.05
intr = 0.1
cor_m = np.array([[1, 0.5], [0.5, 1]])
texp = 1
strike = 0
price_exact = 8.5132252

In [78]:
# MC price based on normal model
# make sure that the prices are similar\

np.random.seed(123456)
price_spread = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, intr=intr, divr=divr, bsm=False)
print(price_spread, price_exact)

8.348852807225292 8.5132252


# Spread option implementation based on BSM model

In [79]:
# You also test Kirk's approximation
price_kirk = basket.spread_price_kirk(strike, spot, vol, texp, 0.5, intr, divr)
print(price_kirk)

8.5132252295455


# [To Do] Complete the implementation of basket_price_norm_analytic
# Compare the MC std of BSM basket prices from with and without CV

In [80]:
# the price from basket.basket_price_norm_analytic should be also similar
# basket.basket_price_norm_analytic(strike, spot, vol*spot, weights, texp, cor_m, intr=intr, divr=divr, bsm=False)